version: '3.5'

services:
  api-backend:
    container_name: api-backend
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5001:80

  frontend:
    container_name: angular-frontend
    build: ./kiosk-app
    volumes:
      - './kiosk-app:/usr/src/app'
    ports:
      - '3000:4200'
    depends_on:
      - api-backend
